export const GLOBAL_COLOR = {
  bgGreen: "#68888A",
  green: "#008080",
  blue: "#1A0E61",
  lightGray: "#E9E9E9",
  gray: "#C0C0C0",
  darkGray: "#403F40",
  shadow: "#818184",
  black: "#0B090A",
};

export const KEY_EVENTS = {
  ENTER: "Enter",
  ARROW_UP: "ArrowUp",
  ARROW_DOWN: "ArrowDown",
  ARROW_LEFT: "ArrowLeft",
  ARROW_RIGHT: "ArrowRight",
  META: "Meta",
};

export const TASK_BAR_HEIGHT = 35;
export const FOLDER_MIN_WIDTH = 200;
export const FOLDER_MIN_HEIGHT = 150;
export const ALLOWED_QUILL = {
  allowedTags: [
    "a",
    "p",
    "s",
    "span",
    "div",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "ul",
    "ol",
    "li",
    "b",
    "i",
    "u",
    "em",
    "strong",
    "strike",
    "sub",
    "sup",
    "hr",
    "br",
    "blockquote",
    "caption",
    "code",
    "pre",
    "col",
    "colgroup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
  ],
  allowedAttributes: {
    span: ["style", "color"],
  },
  allowedClasses: {
    "*": [
      "ql-align-right",
      "ql-align-center",
      "ql-align-justify",
      "ql-code-block",
      "ql-code-block-container",
      "ql-syntax",
      "ql-direction-rtl",
      "ql-font-serif",
      "ql-font-monospace",
      "ql-formula",
      "ql-indent-1",
      "ql-indent-2",
      "ql-indent-3",
      "ql-indent-4",
      "ql-indent-5",
      "ql-indent-6",
      "ql-indent-7",
      "ql-indent-8",
      "ql-size-small",
      "ql-size-large",
      "ql-size-huge",
    ],
  },
};
